#!/usr/bin/env bash
export MALLOC_ARENA_MAX="${MALLOC_ARENA_MAX:-2}"
export SB_LIBDIR="${SB_LIBDIR:-$GAMEDIR/runtime-libs}"
export SB_ASSET_DIR="${SB_ASSET_DIR:-$GAMEDIR/assets}"
export SB_APK="${SB_APK:-$GAMEDIR/assemblies.apk}"
export SB_DATA_DIR="${SB_DATA_DIR:-$GAMEDIR/data}"
export SB_RUNTIME_INIT="${SB_RUNTIME_INIT:-1}"
export SB_START_ACTIVITY="${SB_START_ACTIVITY:-1}"
export SB_HOLD="${SB_HOLD:-1}"
export SB_JNI_VERBOSE="${SB_JNI_VERBOSE:-0}"
export SB_PRESENT_FBO="${SB_PRESENT_FBO:-1}"
export SB_FBO_TRACK="${SB_FBO_TRACK:-1}"
export SB_ASPECT_FILL="${SB_ASPECT_FILL:-1}"
export SB_RIGHT_CURSOR="${SB_RIGHT_CURSOR:-0}"
mkdir -p "$SB_DATA_DIR/cache" "$SB_DATA_DIR/.config/.isolated-storage"
